version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - ./mongodb-init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Monta el script

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  flask-api:
    build:
      context: ./RECOMENDACION
    container_name: flask-api
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
      - redis

  react-frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - REACT_APP_API_URL=http://18.215.183.205:5000 # Usamos una variable de entorno para la URL del API

networks:
  app_network:
