// Crear base de datos
db = db.getSiblingDB('MiBaseDeDatos');  // Usar la base de datos MiBaseDeDatos

// Crear colecciones y agregar datos

// Crear la colección de Usuarios
db.createCollection('Usuarios');
db.Usuarios.insertMany([
    { "ID": 1, "Nombre": "John_Perez" },
    { "ID": 2, "Nombre": "Maria_Lopez" },
    { "ID": 3, "Nombre": "Carlos_Garcia" },
    { "ID": 4, "Nombre": "Anna_Torres" },
    { "ID": 5, "Nombre": "Louis_Mendoza" },
    { "ID": 6, "Nombre": "Laura_Fernandez" },
    { "ID": 7, "Nombre": "Peter_Sanchez" },
    { "ID": 8, "Nombre": "Sophia_Ramirez" },
    { "ID": 9, "Nombre": "Daniel_Silva" },
    { "ID": 10, "Nombre": "Helen_Flores" },
    { "ID": 11, "Nombre": "Antonio_Ruiz" },
    { "ID": 12, "Nombre": "Isabella_Morales" },
    { "ID": 13, "Nombre": "Sebastian_Gonzalez" },
    { "ID": 14, "Nombre": "Camila_Gomez" },
    { "ID": 15, "Nombre": "Diego_Hernandez" },
    { "ID": 16, "Nombre": "Valeria_Ortiz" },
    { "ID": 17, "Nombre": "Mateo_Navarro" },
    { "ID": 18, "Nombre": "Andrea_Soto" },
    { "ID": 19, "Nombre": "Lucas_Guerrero" },
    { "ID": 20, "Nombre": "Juliana_Cruz" },
    { "ID": 21, "Nombre": "Emilio_Martinez" },
    { "ID": 22, "Nombre": "Angela_Rojas" },
    { "ID": 23, "Nombre": "Gabriel_Alvarez" },
    { "ID": 24, "Nombre": "Paula_Serrano" },
    { "ID": 25, "Nombre": "Santiago_Ramos" },
    { "ID": 26, "Nombre": "Victoria_Vega" },
    { "ID": 27, "Nombre": "David_Pena" },
    { "ID": 28, "Nombre": "Monica_Molina" },
    { "ID": 29, "Nombre": "Leonardo_Santos" },
    { "ID": 30, "Nombre": "Sara_Medina" },
    { "ID": 31, "Nombre": "Alejandro_Rivera" },
    { "ID": 32, "Nombre": "Natalia_Suarez" },
    { "ID": 33, "Nombre": "Miguel_Fuentes" },
    { "ID": 34, "Nombre": "Adriana_Moreno" },
    { "ID": 35, "Nombre": "Javier_Cabrera" },
    { "ID": 36, "Nombre": "Carolina_Guzman" },
    { "ID": 37, "Nombre": "Hugo_Reyes" },
    { "ID": 38, "Nombre": "Ximena_Bravo" },
    { "ID": 39, "Nombre": "Ivan_Diaz" },
    { "ID": 40, "Nombre": "Patricia_Fuentes" },
    { "ID": 41, "Nombre": "Francisco_Lara" },
    { "ID": 42, "Nombre": "Antonia_Palacios" },
    { "ID": 43, "Nombre": "Gonzalo_Mendez" },
    { "ID": 44, "Nombre": "Marta_Nieto" },
    { "ID": 45, "Nombre": "Raul_Esparza" },
    { "ID": 46, "Nombre": "Claudia_León" },
    { "ID": 47, "Nombre": "Felipe_Murillo" },
    { "ID": 48, "Nombre": "Elena_Alonso" },
    { "ID": 49, "Nombre": "Samuel_Vargas" },
    { "ID": 50, "Nombre": "Ines_Marquez" },
    { "ID": 51, "Nombre": "Jorge_Serrano" },
    { "ID": 52, "Nombre": "Teresa_Barrera" },
    { "ID": 53, "Nombre": "Marcos_Avila" },
    { "ID": 54, "Nombre": "Alicia_Ramos" },
    { "ID": 55, "Nombre": "Alberto_Navarro" },
    { "ID": 56, "Nombre": "Gloria_Vargas" },
    { "ID": 57, "Nombre": "Fernando_Sanchez" },
    { "ID": 58, "Nombre": "Marina_Campos" },
    { "ID": 59, "Nombre": "Ivan_Castillo" },
    { "ID": 60, "Nombre": "Beatriz_Santana" },
    { "ID": 61, "Nombre": "Oscar_Martinez" },
    { "ID": 62, "Nombre": "Paula_Ruiz" },
    { "ID": 63, "Nombre": "Roberto_Pascual" },
    { "ID": 64, "Nombre": "Ariana_Rojas" },
    { "ID": 65, "Nombre": "Victor_Galvez" },
    { "ID": 66, "Nombre": "Sofia_Martinez" },
    { "ID": 67, "Nombre": "Arturo_Ramirez" },
    { "ID": 68, "Nombre": "Melissa_Suarez" },
    { "ID": 69, "Nombre": "Ricardo_Nuñez" },
    { "ID": 70, "Nombre": "Clara_Lozano" },
    { "ID": 71, "Nombre": "Adrian_Palacios" },
    { "ID": 72, "Nombre": "Aurora_Gonzalez" },
    { "ID": 73, "Nombre": "Luis_Fernandez" },
    { "ID": 74, "Nombre": "Rocio_Rivera" },
    { "ID": 75, "Nombre": "Jesus_Santos" },
    { "ID": 76, "Nombre": "Carmen_Ortega" },
    { "ID": 77, "Nombre": "Ruben_Medina" },
    { "ID": 78, "Nombre": "Esther_Perez" },
    { "ID": 79, "Nombre": "Pablo_Ramos" },
    { "ID": 80, "Nombre": "Yolanda_Navarro" },
    { "ID": 81, "Nombre": "Guillermo_Lara" },
    { "ID": 82, "Nombre": "Clara_Fernandez" },
    { "ID": 83, "Nombre": "Julio_Pena" },
    { "ID": 84, "Nombre": "Alejandra_Alonso" },
    { "ID": 85, "Nombre": "Manuel_Castro" },
    { "ID": 86, "Nombre": "Miriam_Herrera" },
    { "ID": 87, "Nombre": "Francisco_Dominguez" },
    { "ID": 88, "Nombre": "Natalia_Gil" },
    { "ID": 89, "Nombre": "Ignacio_Serrano" },
    { "ID": 90, "Nombre": "Eva_Moya" },
    { "ID": 91, "Nombre": "Gustavo_Morales" },
    { "ID": 92, "Nombre": "Victoria_Barreiro" },
    { "ID": 93, "Nombre": "Andres_Flores" },
    { "ID": 94, "Nombre": "Marta_Garcia" },
    { "ID": 95, "Nombre": "Miguel_Vega" },
    { "ID": 96, "Nombre": "Patricia_Montero" },
    { "ID": 97, "Nombre": "Juan_Lara" },
    { "ID": 98, "Nombre": "Noelia_Gomez" },
    { "ID": 99, "Nombre": "Rodrigo_Ramirez" },
    { "ID": 100, "Nombre": "Ana_Torres" }
]);


// Crear la colección de Skills
db.createCollection('Skills');
db.Skills.insertMany([
    { "ID": 1, "Nombre": "Backend_Programming" },
    { "ID": 2, "Nombre": "Frontend_Programming" },
    { "ID": 3, "Nombre": "Mobile_Programming" },
    { "ID": 4, "Nombre": "Graphic_Design" },
    { "ID": 5, "Nombre": "Project_Management" },
    { "ID": 6, "Nombre": "Service_Management" },
    { "ID": 7, "Nombre": "Data_Analysis" },
    { "ID": 8, "Nombre": "Digital_Marketing" },
    { "ID": 9, "Nombre": "Artificial_Intelligence" },
    { "ID": 10, "Nombre": "Cybersecurity" },
    { "ID": 11, "Nombre": "Machine_Learning" },
    { "ID": 12, "Nombre": "Deep_Learning" },
    { "ID": 13, "Nombre": "Computer_Vision" },
    { "ID": 14, "Nombre": "Natural_Language_Processing" },
    { "ID": 15, "Nombre": "Cloud_Computing" },
    { "ID": 16, "Nombre": "DevOps" },
    { "ID": 17, "Nombre": "Database_Administration" },
    { "ID": 18, "Nombre": "Networking" },
    { "ID": 19, "Nombre": "Software_Architecture" },
    { "ID": 20, "Nombre": "UI_UX_Design" },
    { "ID": 21, "Nombre": "Blockchain_Technology" },
    { "ID": 22, "Nombre": "Big_Data" },
    { "ID": 23, "Nombre": "IoT_Development" },
    { "ID": 24, "Nombre": "Game_Development" },
    { "ID": 25, "Nombre": "Quality_Assurance" },
    { "ID": 26, "Nombre": "Business_Analysis" },
    { "ID": 27, "Nombre": "IT_Support" },
    { "ID": 28, "Nombre": "System_Administration" },
    { "ID": 29, "Nombre": "Information_Security" },
    { "ID": 30, "Nombre": "Enterprise_Architecture" }
]);


// Crear la colección de UsuarioSkills
db.createCollection('UsuarioSkills');
db.UsuarioSkills.insertMany([
    { "ID": 1, "ID_Usuario": 1, "ID_Skill": 1, "Puntuacion": 95 },
    { "ID": 2, "ID_Usuario": 2, "ID_Skill": 2, "Puntuacion": 88 },
    { "ID": 3, "ID_Usuario": 3, "ID_Skill": 3, "Puntuacion": 92 },
    { "ID": 4, "ID_Usuario": 4, "ID_Skill": 4, "Puntuacion": 90 },
    { "ID": 5, "ID_Usuario": 5, "ID_Skill": 5, "Puntuacion": 96 },
    { "ID": 6, "ID_Usuario": 6, "ID_Skill": 6, "Puntuacion": 89 },
    { "ID": 7, "ID_Usuario": 7, "ID_Skill": 7, "Puntuacion": 91 },
    { "ID": 8, "ID_Usuario": 8, "ID_Skill": 8, "Puntuacion": 85 },
    { "ID": 9, "ID_Usuario": 9, "ID_Skill": 9, "Puntuacion": 93 },
    { "ID": 10, "ID_Usuario": 10, "ID_Skill": 10, "Puntuacion": 87 },
    { "ID": 11, "ID_Usuario": 1, "ID_Skill": 2, "Puntuacion": 80 },
    { "ID": 12, "ID_Usuario": 2, "ID_Skill": 3, "Puntuacion": 76 },
    { "ID": 13, "ID_Usuario": 3, "ID_Skill": 1, "Puntuacion": 78 },
    { "ID": 14, "ID_Usuario": 4, "ID_Skill": 5, "Puntuacion": 83 },
    { "ID": 15, "ID_Usuario": 5, "ID_Skill": 6, "Puntuacion": 75 },
    { "ID": 16, "ID_Usuario": 6, "ID_Skill": 9, "Puntuacion": 90 },
    { "ID": 17, "ID_Usuario": 7, "ID_Skill": 10, "Puntuacion": 82 },
    { "ID": 18, "ID_Usuario": 8, "ID_Skill": 1, "Puntuacion": 88 },
    { "ID": 19, "ID_Usuario": 9, "ID_Skill": 8, "Puntuacion": 86 },
    { "ID": 20, "ID_Usuario": 10, "ID_Skill": 7, "Puntuacion": 79 },
    { "ID": 21, "ID_Usuario": 11, "ID_Skill": 11, "Puntuacion": 94 },
    { "ID": 22, "ID_Usuario": 12, "ID_Skill": 12, "Puntuacion": 87 },
    { "ID": 23, "ID_Usuario": 13, "ID_Skill": 13, "Puntuacion": 92 },
    { "ID": 24, "ID_Usuario": 14, "ID_Skill": 14, "Puntuacion": 85 },
    { "ID": 25, "ID_Usuario": 15, "ID_Skill": 15, "Puntuacion": 90 },
    { "ID": 26, "ID_Usuario": 16, "ID_Skill": 16, "Puntuacion": 93 },
    { "ID": 27, "ID_Usuario": 17, "ID_Skill": 17, "Puntuacion": 89 },
    { "ID": 28, "ID_Usuario": 18, "ID_Skill": 18, "Puntuacion": 84 },
    { "ID": 29, "ID_Usuario": 19, "ID_Skill": 19, "Puntuacion": 95 },
    { "ID": 30, "ID_Usuario": 20, "ID_Skill": 20, "Puntuacion": 91 },
    { "ID": 31, "ID_Usuario": 21, "ID_Skill": 21, "Puntuacion": 88 },
    { "ID": 32, "ID_Usuario": 22, "ID_Skill": 22, "Puntuacion": 90 },
    { "ID": 33, "ID_Usuario": 23, "ID_Skill": 23, "Puntuacion": 87 },
    { "ID": 34, "ID_Usuario": 24, "ID_Skill": 24, "Puntuacion": 86 },
    { "ID": 35, "ID_Usuario": 25, "ID_Skill": 25, "Puntuacion": 89 },
    { "ID": 36, "ID_Usuario": 26, "ID_Skill": 26, "Puntuacion": 84 },
    { "ID": 37, "ID_Usuario": 27, "ID_Skill": 27, "Puntuacion": 85 },
    { "ID": 38, "ID_Usuario": 28, "ID_Skill": 28, "Puntuacion": 92 },
    { "ID": 39, "ID_Usuario": 29, "ID_Skill": 29, "Puntuacion": 93 },
    { "ID": 40, "ID_Usuario": 30, "ID_Skill": 30, "Puntuacion": 91 },
    { "ID": 41, "ID_Usuario": 31, "ID_Skill": 11, "Puntuacion": 90 },
    { "ID": 42, "ID_Usuario": 32, "ID_Skill": 12, "Puntuacion": 88 },
    { "ID": 43, "ID_Usuario": 33, "ID_Skill": 13, "Puntuacion": 87 },
    { "ID": 44, "ID_Usuario": 34, "ID_Skill": 14, "Puntuacion": 84 },
    { "ID": 45, "ID_Usuario": 35, "ID_Skill": 15, "Puntuacion": 86 },
    { "ID": 46, "ID_Usuario": 36, "ID_Skill": 16, "Puntuacion": 89 },
    { "ID": 47, "ID_Usuario": 37, "ID_Skill": 17, "Puntuacion": 93 },
    { "ID": 48, "ID_Usuario": 38, "ID_Skill": 18, "Puntuacion": 92 },
    { "ID": 49, "ID_Usuario": 39, "ID_Skill": 19, "Puntuacion": 88 },
    { "ID": 50, "ID_Usuario": 40, "ID_Skill": 20, "Puntuacion": 85 },
    { "ID": 51, "ID_Usuario": 41, "ID_Skill": 21, "Puntuacion": 87 },
    { "ID": 52, "ID_Usuario": 42, "ID_Skill": 22, "Puntuacion": 89 },
    { "ID": 53, "ID_Usuario": 43, "ID_Skill": 23, "Puntuacion": 92 },
    { "ID": 54, "ID_Usuario": 44, "ID_Skill": 24, "Puntuacion": 90 },
    { "ID": 55, "ID_Usuario": 45, "ID_Skill": 25, "Puntuacion": 91 },
    { "ID": 56, "ID_Usuario": 46, "ID_Skill": 26, "Puntuacion": 89 },
    { "ID": 57, "ID_Usuario": 47, "ID_Skill": 27, "Puntuacion": 90 },
    { "ID": 58, "ID_Usuario": 48, "ID_Skill": 28, "Puntuacion": 86 },
    { "ID": 59, "ID_Usuario": 49, "ID_Skill": 29, "Puntuacion": 88 },
    { "ID": 60, "ID_Usuario": 50, "ID_Skill": 30, "Puntuacion": 84 },
    { "ID": 61, "ID_Usuario": 11, "ID_Skill": 22, "Puntuacion": 89 },
    { "ID": 62, "ID_Usuario": 22, "ID_Skill": 19, "Puntuacion": 92 },
    { "ID": 63, "ID_Usuario": 33, "ID_Skill": 12, "Puntuacion": 85 },
    { "ID": 64, "ID_Usuario": 44, "ID_Skill": 18, "Puntuacion": 91 },
    { "ID": 65, "ID_Usuario": 55, "ID_Skill": 13, "Puntuacion": 93 },
    { "ID": 66, "ID_Usuario": 66, "ID_Skill": 11, "Puntuacion": 94 },
    { "ID": 67, "ID_Usuario": 77, "ID_Skill": 23, "Puntuacion": 86 },
    { "ID": 68, "ID_Usuario": 88, "ID_Skill": 17, "Puntuacion": 92 },
    { "ID": 69, "ID_Usuario": 99, "ID_Skill": 15, "Puntuacion": 87 },
    { "ID": 70, "ID_Usuario": 1, "ID_Skill": 14, "Puntuacion": 83 },
    { "ID": 71, "ID_Usuario": 23, "ID_Skill": 12, "Puntuacion": 89 },
    { "ID": 72, "ID_Usuario": 34, "ID_Skill": 11, "Puntuacion": 91 },
    { "ID": 73, "ID_Usuario": 45, "ID_Skill": 20, "Puntuacion": 90 },
    { "ID": 74, "ID_Usuario": 56, "ID_Skill": 21, "Puntuacion": 84 },
    { "ID": 75, "ID_Usuario": 67, "ID_Skill": 16, "Puntuacion": 93 },
    { "ID": 76, "ID_Usuario": 78, "ID_Skill": 27, "Puntuacion": 88 },
    { "ID": 77, "ID_Usuario": 89, "ID_Skill": 25, "Puntuacion": 92 },
    { "ID": 78, "ID_Usuario": 100, "ID_Skill": 28, "Puntuacion": 86 },
    { "ID": 79, "ID_Usuario": 10, "ID_Skill": 24, "Puntuacion": 83 },
    { "ID": 80, "ID_Usuario": 20, "ID_Skill": 22, "Puntuacion": 90 },
    { "ID": 81, "ID_Usuario": 30, "ID_Skill": 18, "Puntuacion": 89 },
    { "ID": 82, "ID_Usuario": 40, "ID_Skill": 19, "Puntuacion": 92 },
    { "ID": 83, "ID_Usuario": 50, "ID_Skill": 30, "Puntuacion": 93 },
    { "ID": 84, "ID_Usuario": 60, "ID_Skill": 29, "Puntuacion": 94 },
    { "ID": 85, "ID_Usuario": 70, "ID_Skill": 28, "Puntuacion": 90 },
    { "ID": 86, "ID_Usuario": 80, "ID_Skill": 27, "Puntuacion": 85 },
    { "ID": 87, "ID_Usuario": 90, "ID_Skill": 26, "Puntuacion": 88 },
    { "ID": 88, "ID_Usuario": 100, "ID_Skill": 23, "Puntuacion": 91 },
    { "ID": 89, "ID_Usuario": 90, "ID_Skill": 15, "Puntuacion": 87 },
    { "ID": 90, "ID_Usuario": 80, "ID_Skill": 22, "Puntuacion": 83 },
    { "ID": 91, "ID_Usuario": 70, "ID_Skill": 19, "Puntuacion": 91 },
    { "ID": 92, "ID_Usuario": 60, "ID_Skill": 17, "Puntuacion": 90 },
    { "ID": 93, "ID_Usuario": 50, "ID_Skill": 12, "Puntuacion": 92 },
    { "ID": 94, "ID_Usuario": 40, "ID_Skill": 14, "Puntuacion": 84 },
    { "ID": 95, "ID_Usuario": 30, "ID_Skill": 11, "Puntuacion": 94 },
    { "ID": 96, "ID_Usuario": 20, "ID_Skill": 10, "Puntuacion": 89 },
    { "ID": 97, "ID_Usuario": 10, "ID_Skill": 9, "Puntuacion": 88 },
    { "ID": 98, "ID_Usuario": 100, "ID_Skill": 15, "Puntuacion": 93 },
    { "ID": 99, "ID_Usuario": 90, "ID_Skill": 20, "Puntuacion": 91 },
    { "ID": 100, "ID_Usuario": 80, "ID_Skill": 22, "Puntuacion": 92 }
]);
