# Dockerfile para SQL Server
FROM mcr.microsoft.com/mssql/server:2022-latest


# Establece las variables de entorno para configurar la base de datos
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=StrongPassword123
ENV MSSQL_PID=Express


# Exponer el puerto 1433 para SQL Server
EXPOSE 1433